### ISSUE TITLE
Form submission broken with duplicate number larger than 10

### ISSUE THREAD

**Issue by jhdvc** [inspiredminds/contao-fieldset-duplication#29]
Submitting a form where a fieldset has been duplicated more than 10 times results in a form validation error preventing the form from being submitted.

This is due to the way `$duplicateNumber` ist being calculated in `\EventListener\FormHookListener::onCompileFormFields`on line 121.

Given a field with name "field_a" the name of the elevenths duplication is "field_a_duplication_10". `(substr($duplicateName, -1))` returns 0 instead of 10.

**Comment by fritzmg** [comment]
Should be fixed in `2.1.0` now.
