### ISSUE TITLE
Error with javascript template

### ISSUE THREAD

**Issue by johannes-bittner** [inspiredminds/contao-fieldset-duplication#4]
Very nice and useful extension!

When using the original javascript template ( j_fieldset_duplication.html5), the buttons are not shown and the console log says: 

> Uncaught SyntaxError: Unexpected identifier

Uncommenting the lines 8/10 [buttonAdd: '+' / buttonRemove: '&times;'] solves the problem.

**Comment by fritzmg** [comment]
Hm, I cannot confirm that. Which browser in which version?

**Comment by johannes-bittner** [comment]
Template: 
![grafik](https://user-images.githubusercontent.com/1597697/92090621-ebe6b500-edcf-11ea-99c2-0e5628a4c9cc.png)
Console Chrome 84/85, Windows 10: 

![grafik](https://user-images.githubusercontent.com/1597697/92090725-0fa9fb00-edd0-11ea-986b-a06332b57c4b.png)

I had to create the template in the backend and to uncomment the two lines in order to have the icons displayed.

**Comment by fritzmg** [comment]
Ah, you copy & pasted the custom options of the README, which have this error. The default template looks like this: https://github.com/inspiredminds/contao-fieldset-duplication/blob/master/src/Resources/contao/templates/j_fieldset_duplication.html5

The error in the README is fixed now.
